import { Sidebar } from '@/components/feat/Header'
import { GeistSans } from 'geist/font/sans'
import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <div className='flex w-full'>
          <Sidebar className='border-r' />
          {children}
        </div>
      </body>
    </html>
  )
}
